const weapons: Weapon[] = [
  {
    name: 'dagger',
    cost: 5,
    effect: 'none',
    class: [
      'fighter',
      'priest',
      'mage',
      'thief',
      'bishop',
      'samurai',
      'lord',
      'ninja',
    ],
    damageMin: 1,
    damageMax: 4,
  },
  {
    name: 'Staff',
    cost: 10,
    damageMin: 1,
    damageMax: 5,
    effect: '-',
    class: [
      'fighter',
      'priest',
      'thief',
      'mage',
      'bishop',
      'samurai',
      'lord',
      'ninja',
    ],
  },
  {
    name: 'Short Sword',
    cost: 15,
    damageMin: 1,
    damageMax: 6,
    effect: '-',
    class: ['fighter', 'thief', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Long Sword',
    cost: 25,
    damageMin: 1.5,
    damageMax: 8,
    effect: '-',
    class: ['fighter', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Anointed Mace',
    cost: 30,
    damageMin: 2,
    damageMax: 6,
    effect: '-',
    class: ['fighter', 'priest', 'bishop', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Anointed Flail',
    cost: 150,
    damageMin: 1,
    damageMax: 7,
    effect: '-',
    class: ['fighter', 'priest', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Staff +2 / Studly Staff',
    cost: 2500,
    damageMin: 3,
    damageMax: 6,
    effect: '-',
    class: [
      'fighter',
      'priest',
      'thief',
      'mage',
      'bishop',
      'samurai',
      'lord',
      'ninja',
    ],
  },
  {
    name: 'Staff of Mogref / Rod of Iron',
    cost: 3000,
    damageMin: 1,
    damageMax: 6,
    effect: 'Casts MOGREF',
    class: ['mage', 'bishop'],
  },
  {
    name: 'Short Sword +2 / Epee[1] of Exelence',
    cost: 4000,
    damageMin: 3,
    damageMax: 8,
    effect: '-',
    class: ['fighter', 'thief', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Mace +2 / Mace of Power',
    cost: 4000,
    damageMin: 3.5,
    damageMax: 10,
    effect: '-',
    class: ['fighter', 'priest', 'bishop', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Long Sword +2 / Sword of Slashing',
    cost: 4000,
    damageMin: 3,
    damageMax: 12,
    effect: '-',
    class: ['fighter', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Short Sword -2 / Epee[2] of Disaster',
    cost: 8000,
    damageMin: 1.0,
    damageMax: 6.0,
    effect: '-',
    class: ['fighter', 'thief', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Dagger +2 / Dagger of Slicing',
    cost: 8000,
    damageMin: 3.0,
    damageMax: 6.0,
    effect: '',
    class: ['fighter', 'thief', 'mage', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Mace Pro Poison / Mace of Snakes',
    cost: 10000,
    damageMin: 1.0,
    damageMax: 8.0,
    effect: 'Prot: Insect; Res: Poison',
    class: ['fighter', 'priest', 'bishop', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Mage Masher',
    cost: 10000,
    damageMin: 2.0,
    damageMax: 7.0,
    effect: 'Prot: Mage',
    class: ['fighter', 'thief', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Long Sword +1 / Sword of Slicing',
    cost: 10000,
    damageMin: 2.0,
    damageMax: 9.0,
    effect: '',
    class: ['fighter', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Were Slayer',
    cost: 10000,
    damageMin: 2.0,
    damageMax: 11.0,
    effect: 'Prot and Vs: Were',
    class: ['fighter', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Dragon Slayer',
    cost: 10000,
    damageMin: 2.0,
    damageMax: 11.0,
    effect: 'Prot and Vs: Dragon',
    class: ['fighter', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Mace +1 / Mace of Pounding',
    cost: 12500,
    damageMin: 3.0,
    damageMax: 9.0,
    effect: '',
    class: ['fighter', 'priest', 'bishop', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Staff/Montino / Rod of Silence',
    cost: 15000,
    damageMin: 2.0,
    damageMax: 6.0,
    effect: 'Casts MONTINO',
    class: [
      'fighter',
      'priest',
      'thief',
      'mage',
      'bishop',
      'samurai',
      'lord',
      'ninja',
    ],
  },
  {
    name: 'Short Sword +1 / Blade of Bitting',
    cost: 15000,
    damageMin: 2,
    damageMax: 7,
    effect: '',
    class: ['fighter', 'thief', 'samurai', 'lord', 'ninja'],
  },
  {
    name: "Blade Cusinart'",
    cost: 15000,
    damageMin: 10,
    damageMax: 12,
    effect: '',
    class: ['fighter', 'samurai', 'lord', 'ninja'],
  },
  {
    name: 'Dagger of Speed',
    cost: 30000,
    damageMin: 1,
    damageMax: 4,
    effect: 'AC: 3',
    class: ['mage', 'ninja'],
  },
  {
    name: 'Evil Sword +3 / Saber of Evil',
    cost: 50000,
    damageMin: 4,
    damageMax: 13,
    effect: 'Alig: Evil',
    class: ['fighter'],
  },
  {
    name: 'Evil S-Sword +3 / Soul Slayer',
    cost: 50000,
    damageMin: 1,
    damageMax: 6,
    effect: 'Alig: Evil',
    class: ['fighter'],
  },
  {
    name: 'Thieves Dagger',
    cost: 50000,
    damageMin: 1,
    damageMax: 6,
    effect: 'Invoke: Class to Ninja',
    class: [],
  },
  {
    name: 'Shuriken',
    cost: 50000,
    damageMin: 11,
    damageMax: 16,
    effect: 'Alig: Evil; Res: Poison. LvlDrain; Invoking: Hp+1.',
    class: [],
  },
  {
    name: 'Muramasa Blade',
    cost: 1000000,
    damageMin: 10,
    damageMax: 50,
    effect: 'Invoking: St+1',
    class: [],
  },
];

export default weapons;
